"""added the lead and understudy

Revision ID: c4d6a2d7a658
Revises: 4b53ea235d0a
Create Date: 2023-09-09 00:28:22.801015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d6a2d7a658'
down_revision = '4b53ea235d0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_auditions_role_id_roles'), 'auditions', 'roles', ['role_id'], ['id'])
    op.drop_column('auditions', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditions', sa.Column('role', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_auditions_role_id_roles'), 'auditions', type_='foreignkey')
    # ### end Alembic commands ###
